# Generated by Django 5.1.4 on 2025-01-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disastertable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetable',
            name='Details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcetable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.logintable'),
        ),
        migrations.AlterField(
            model_name='resourcetable',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcetable',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
