# Generated by Django 5.1.4 on 2024-12-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skilltable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='Skill',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='SkillTable',
        ),
    ]
