# Generated by Django 5.1.4 on 2025-01-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resourcetable_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Task', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
