# Generated by Django 5.1.4 on 2024-12-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skilltable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationtable',
            old_name='Donation',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='donationtable',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
