# Generated by Django 5.1.4 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tasktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
