# Generated by Django 5.1.4 on 2025-01-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tasktable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktable',
            name='USERID',
        ),
        migrations.CreateModel(
            name='AssignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('TASK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tasktable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
