# Generated by Django 5.1.4 on 2025-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_donationtable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='disastertable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
