# Generated by Django 5.1.4 on 2025-01-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_disastertable_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resourcelimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodlimit', models.CharField(blank=True, max_length=100, null=True)),
                ('clothlimit', models.CharField(blank=True, max_length=100, null=True)),
                ('medicallimit', models.CharField(blank=True, max_length=100, null=True)),
                ('shelterlimit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
