# Generated by Django 5.1.4 on 2025-01-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_resourcelimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelimit',
            old_name='clothlimit',
            new_name='resourcecategory',
        ),
        migrations.RenameField(
            model_name='resourcelimit',
            old_name='foodlimit',
            new_name='resourcelimit',
        ),
        migrations.RemoveField(
            model_name='resourcelimit',
            name='medicallimit',
        ),
        migrations.RemoveField(
            model_name='resourcelimit',
            name='shelterlimit',
        ),
        migrations.AlterField(
            model_name='resourcetable',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.resourcelimit'),
        ),
    ]
