# Generated by Django 5.1.4 on 2025-01-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_clothlimit_resourcelimit_resourcecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelimit',
            name='resourcepercentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
